### ISSUE TITLE
[Roadmap] 2019 - Q1

### ISSUE THREAD

**Issue by newmuis** [ampproject/wg-stories#1]
Stories Working Group's focus for Q1 of 2019 is improving stability and providing features that users of AMP or users of stories would expect.

- [ ] Media playback reliability ampproject/amphtml#16534
- [ ] Deprecate amp-story 0.1 ampproject/amphtml#14357
- [ ] Support `<amp-story-page>` attachments (ability to swipe up to more content) ampproject/amphtml#20209
- [ ] Paywall support ampproject/amphtml#12180
- [ ] Enable video playback from players other than `<amp-video>` ampproject/amphtml#15847
- [ ] Support iframe-based components ampproject/amphtml#19213
- [ ] Full screen experience ampproject/amphtml#18986
- [ ] Support `<amp-live-list>` ampproject/amphtml#18624
- [ ] Update translations ampproject/amphtml#20344
- [ ] Story animation parameterization ampproject/amphtml#20260
- [ ] Branching ampproject/amphtml#12183
- [ ] Sharing link to a specific page ampproject/amphtml#12182
- [ ] Sponsored stories ampproject/amphtml#14372

**Comment by newmuis** [comment]
Closed in favor of #10, the new quarterly roadmap.
